name: ${project.name}
main: org.battleplugins.survivalarena.SurvivalArenaPlugin
depend: [BattleArena]
api-version: 1.13
authors: [Stryker76, BattlePlugins]
description: ${project.description}
commands:
  sa:
    aliases: [survivalarena]